export const INSPECTION_HANDOFF_FIELD_LABELS = {
  customer_name: "Customer / job name",
  property_name: "Property / job name",
  service_address: "Service address",
  project_contact_first_name: "Contact first name",
  project_contact_last_name: "Contact last name",
  project_contact_phone: "Contact phone",
  project_contact_email: "Contact email",
  customer_requests: "Customer request",
  property_type: "Property type",
  story_count: "Building height",
  construction_type: "Existing roof or new construction",
  roofing_system: "Existing roofing system",
  roof_areas: "Roof areas / sections",
  work_type: "Work type",
  measurements: "Measurements / square footage / squares",
  roof_measurement_notes: "Roof measurement notes",
  existing_layers: "Existing layers",
  scope_of_work: "Recommended scope",
  material_specifications: "Material / system specifications",
  special_conditions: "Risks or special conditions",
  roof_access_details: "Roof and property access",
  equipment_requirements: "Equipment requirements",
  hvac_requirements: "HVAC requirements",
  subcontractor_requirements: "Subcontractors",
  permit_requirements: "Permit requirements",
  overspray_risk_notes: "Overspray risk",
  exclusions: "Exclusions",
  alternates: "Alternates / optional work",
  verbal_commitments: "Anything discussed or promised",
  customer_deadline: "Customer deadline",
  estimated_crew_size: "Estimated crew size",
  estimated_working_days: "Estimated working days",
};
