BEGIN;
CREATE TABLE public.inspection_requests (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 request_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
 created_by uuid NOT NULL REFERENCES public.user_profiles(id),
 assigned_to uuid REFERENCES public.user_profiles(id),
 lead_id uuid REFERENCES public.crm_leads(id),
 task_id uuid UNIQUE REFERENCES public.company_tasks(id) ON DELETE SET NULL,
 proposal_request_id uuid UNIQUE REFERENCES public.proposal_requests(id),
 status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','new','contacted','scheduled','inspected','proposal_requested','on_hold','cancelled')),
 contact_name text NOT NULL DEFAULT '',phone text NOT NULL DEFAULT '',email text NOT NULL DEFAULT '',property_address text NOT NULL DEFAULT '',
 best_time_to_call text NOT NULL DEFAULT '',urgency text NOT NULL DEFAULT 'Normal' CHECK(urgency IN ('Normal','High','Urgent')),
 notes text NOT NULL DEFAULT '',findings text NOT NULL DEFAULT '',measurements text NOT NULL DEFAULT '',
 appointment_at timestamptz,submitted_at timestamptz,contacted_at timestamptz,inspected_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version integer NOT NULL DEFAULT 1
);
CREATE INDEX inspection_requests_queue_idx ON public.inspection_requests(assigned_to,status,appointment_at);
ALTER TABLE public.inspection_requests ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.can_read_inspection_request(p_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
 SELECT EXISTS(SELECT 1 FROM public.inspection_requests r WHERE r.id=p_id AND auth.uid() IS NOT NULL AND (
 r.created_by=auth.uid() OR (r.status<>'draft' AND (r.assigned_to=auth.uid() OR public.is_proposal_manager()
 OR (r.proposal_request_id IS NOT NULL AND public.can_access_proposal_request(r.proposal_request_id))))));
$$;
CREATE FUNCTION public.can_edit_inspection_request(p_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
 SELECT EXISTS(SELECT 1 FROM public.inspection_requests r WHERE r.id=p_id AND auth.uid() IS NOT NULL AND (
 r.created_by=auth.uid() OR (r.status<>'draft' AND (r.assigned_to=auth.uid() OR public.is_proposal_manager()))));
$$;
REVOKE ALL ON FUNCTION public.can_read_inspection_request(uuid),public.can_edit_inspection_request(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.can_read_inspection_request(uuid),public.can_edit_inspection_request(uuid) TO authenticated;
REVOKE ALL ON public.inspection_requests FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.inspection_requests TO authenticated;
GRANT ALL ON public.inspection_requests TO service_role;
CREATE POLICY inspection_requests_read ON public.inspection_requests FOR SELECT TO authenticated USING(public.can_read_inspection_request(id));

CREATE TABLE public.inspection_request_audit (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),inspection_request_id uuid NOT NULL REFERENCES public.inspection_requests(id),
 actor_id uuid REFERENCES public.user_profiles(id),action text NOT NULL,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX inspection_audit_request_idx ON public.inspection_request_audit(inspection_request_id,created_at);
ALTER TABLE public.inspection_request_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.inspection_request_audit FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.inspection_request_audit TO authenticated;GRANT ALL ON public.inspection_request_audit TO service_role;
CREATE POLICY inspection_audit_read ON public.inspection_request_audit FOR SELECT TO authenticated USING(public.can_read_inspection_request(inspection_request_id));
CREATE FUNCTION public.audit_inspection_request() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
 INSERT INTO public.inspection_request_audit(inspection_request_id,actor_id,action,details)
 VALUES(NEW.id,auth.uid(),CASE WHEN TG_OP='INSERT' THEN 'created' WHEN OLD.status IS DISTINCT FROM NEW.status THEN 'status_changed' ELSE 'updated' END,
 jsonb_build_object('before',CASE WHEN TG_OP='INSERT' THEN NULL ELSE to_jsonb(OLD) END,'after',to_jsonb(NEW)));
 IF TG_OP='UPDATE' AND NEW.status<>'draft' AND OLD.status<>'draft' AND NEW.assigned_to IS DISTINCT FROM OLD.assigned_to AND NEW.assigned_to IS NOT NULL THEN
  INSERT INTO public.workflow_notifications(event_key,user_id,source_record_uid,kind,message)
  VALUES('inspection_reassigned:'||NEW.id||':'||NEW.version,NEW.assigned_to,NEW.id::text,'inspection_assignment','Inspection IR-'||NEW.request_number||' was assigned to you. Open the Inspection Request Center for customer details and files.') ON CONFLICT(event_key,user_id) DO NOTHING;
 END IF;
 RETURN NEW;
END;$$;
REVOKE ALL ON FUNCTION public.audit_inspection_request() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER inspection_request_audit AFTER INSERT OR UPDATE ON public.inspection_requests FOR EACH ROW EXECUTE FUNCTION public.audit_inspection_request();

CREATE FUNCTION public.save_inspection_request(p_id uuid,p_payload jsonb,p_expected_version integer DEFAULT 0)
RETURNS public.inspection_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE r public.inspection_requests; technician uuid;
BEGIN
 IF auth.uid() IS NULL OR NOT public.can_use_crm() THEN RAISE EXCEPTION 'Inspection request access required'; END IF;
 IF p_id IS NULL OR p_payload IS NULL OR jsonb_typeof(p_payload)<>'object' THEN RAISE EXCEPTION 'Invalid request'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_id::text,0));
 SELECT * INTO r FROM public.inspection_requests WHERE id=p_id FOR UPDATE;
 IF FOUND THEN
  IF NOT public.can_edit_inspection_request(p_id) THEN RAISE EXCEPTION 'Request access required'; END IF;
  IF r.status IN ('proposal_requested','cancelled') THEN RAISE EXCEPTION 'This request is closed for editing'; END IF;
  IF r.version IS DISTINCT FROM p_expected_version THEN RAISE EXCEPTION 'This request changed. Reload before saving.' USING ERRCODE='40001'; END IF;
 ELSE
  IF p_expected_version<>0 THEN RAISE EXCEPTION 'Saved request not found'; END IF;
  SELECT id INTO technician FROM public.user_profiles WHERE lower(email)='ivan@crtroofing.com' AND is_active=true LIMIT 1;
  INSERT INTO public.inspection_requests(id,created_by,assigned_to) VALUES(p_id,auth.uid(),technician) RETURNING * INTO r;
 END IF;
 technician:=coalesce(nullif(p_payload->>'assigned_to','')::uuid,r.assigned_to);
 IF technician IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.user_profiles WHERE id=technician AND is_active=true AND lower(role) IN ('salesperson','estimator','admin','cfo')) THEN RAISE EXCEPTION 'Choose an active sales technician'; END IF;
 IF technician IS DISTINCT FROM r.assigned_to AND NOT public.is_proposal_manager() AND r.status<>'draft' THEN RAISE EXCEPTION 'Office staff must reassign submitted inspections'; END IF;
 UPDATE public.inspection_requests SET contact_name=left(coalesce(p_payload->>'contact_name',r.contact_name),300),
 phone=left(coalesce(p_payload->>'phone',r.phone),100),email=left(coalesce(p_payload->>'email',r.email),300),
 property_address=left(coalesce(p_payload->>'property_address',r.property_address),1000),best_time_to_call=left(coalesce(p_payload->>'best_time_to_call',r.best_time_to_call),300),
 urgency=coalesce(p_payload->>'urgency',r.urgency),notes=left(coalesce(p_payload->>'notes',r.notes),30000),
 findings=left(coalesce(p_payload->>'findings',r.findings),30000),measurements=left(coalesce(p_payload->>'measurements',r.measurements),10000),
 assigned_to=technician,appointment_at=CASE WHEN p_payload ? 'appointment_at' THEN nullif(p_payload->>'appointment_at','')::timestamptz ELSE r.appointment_at END,
 updated_at=now(),version=version+1 WHERE id=p_id RETURNING * INTO r;
 RETURN r;
END;$$;

CREATE FUNCTION public.submit_inspection_request(p_id uuid,p_expected_version integer)
RETURNS public.inspection_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE r public.inspection_requests;t public.company_tasks;actor public.user_profiles;new_lead uuid;
BEGIN
 SELECT * INTO r FROM public.inspection_requests WHERE id=p_id FOR UPDATE;
 IF NOT FOUND OR auth.uid() IS NULL OR r.created_by<>auth.uid() THEN RAISE EXCEPTION 'Only the creator can submit this draft'; END IF;
 IF r.status<>'draft' THEN RETURN r; END IF;
 IF r.version IS DISTINCT FROM p_expected_version THEN RAISE EXCEPTION 'This draft changed. Reload before sending.'; END IF;
 IF trim(r.contact_name)='' OR (trim(r.phone)='' AND trim(r.email)='' AND trim(r.property_address)='') THEN RAISE EXCEPTION 'Enter a contact name and phone, email, or address'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.user_profiles WHERE id=r.assigned_to AND is_active=true) THEN RAISE EXCEPTION 'Assign an active technician'; END IF;
 SELECT * INTO actor FROM public.user_profiles WHERE id=auth.uid();
 new_lead:=r.lead_id;
 IF new_lead IS NULL THEN
  new_lead:=gen_random_uuid();
  INSERT INTO public.crm_leads(id,created_by,originator_id,originator_name,originator_email,relationship_owner_id,assigned_staff_id,
  contact_name,phone,email,property_address,lead_source,service_needed,quick_note,status,qualification_status,qualified_at,qualified_by,accepted_for_inspection_at,accepted_for_inspection_by,updated_by)
  VALUES(new_lead,auth.uid(),auth.uid(),coalesce(actor.full_name,''),coalesce(actor.email,''),auth.uid(),r.assigned_to::text,
  r.contact_name,r.phone,r.email,r.property_address,'Phone Call / Office','Roof inspection',r.notes,'Inspection Requested','qualified',now(),auth.uid(),now(),auth.uid(),auth.uid());
 END IF;
 UPDATE public.inspection_requests SET lead_id=new_lead WHERE id=p_id;
 SELECT * INTO t FROM public.create_inspection_request_task(new_lead,'Inspection Request: '||r.contact_name,
 concat_ws(E'\n','Please contact this customer to schedule a roof inspection.','Contact: '||r.contact_name,'Phone: '||r.phone,'Email: '||r.email,
 'Property address: '||r.property_address,'Best time to call: '||r.best_time_to_call,'Inspection notes: '||r.notes,'Open the Inspection Request Center for photos, files and scheduling.','CRM lead ID: '||new_lead),
 CASE WHEN r.urgency IN ('High','Urgent') THEN 'high' ELSE 'normal' END,r.assigned_to);
 UPDATE public.inspection_requests SET status='new',lead_id=new_lead,task_id=t.id,submitted_at=now(),updated_at=now(),version=version+1 WHERE id=p_id RETURNING * INTO r;
 RETURN r;
END;$$;

CREATE FUNCTION public.transition_inspection_request(p_id uuid,p_status text,p_expected_version integer)
RETURNS public.inspection_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE r public.inspection_requests;
BEGIN
 SELECT * INTO r FROM public.inspection_requests WHERE id=p_id FOR UPDATE;
 IF NOT FOUND OR NOT public.can_edit_inspection_request(p_id) THEN RAISE EXCEPTION 'Request access required'; END IF;
 IF r.status=p_status THEN RETURN r; END IF;
 IF r.version IS DISTINCT FROM p_expected_version THEN RAISE EXCEPTION 'This request changed. Reload before updating.'; END IF;
 IF r.status IN ('draft','proposal_requested','cancelled') OR p_status NOT IN ('contacted','scheduled','inspected','on_hold','cancelled') THEN RAISE EXCEPTION 'Invalid status change'; END IF;
 IF p_status='scheduled' AND r.appointment_at IS NULL THEN RAISE EXCEPTION 'Save an appointment time before scheduling'; END IF;
 IF p_status='inspected' AND (r.assigned_to IS DISTINCT FROM auth.uid() AND NOT public.is_proposal_manager()) THEN RAISE EXCEPTION 'Assigned technician or office confirmation required'; END IF;
 IF p_status='inspected' AND trim(r.findings)='' THEN RAISE EXCEPTION 'Record inspection findings before marking inspected'; END IF;
 UPDATE public.inspection_requests SET status=p_status,
 contacted_at=CASE WHEN p_status='contacted' THEN coalesce(contacted_at,now()) ELSE contacted_at END,
 inspected_at=CASE WHEN p_status='inspected' THEN coalesce(inspected_at,now()) ELSE inspected_at END,
 updated_at=now(),version=version+1 WHERE id=p_id RETURNING * INTO r;
 RETURN r;
END;$$;

INSERT INTO storage.buckets(id,name,public,file_size_limit) VALUES('inspection-attachments','inspection-attachments',false,26214400)
ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=26214400;
CREATE TABLE public.inspection_request_attachments (
 id uuid PRIMARY KEY,inspection_request_id uuid NOT NULL REFERENCES public.inspection_requests(id),
 uploaded_by uuid NOT NULL REFERENCES public.user_profiles(id),storage_path text NOT NULL UNIQUE,
 file_name text NOT NULL CHECK(length(file_name) BETWEEN 1 AND 255),file_size bigint NOT NULL CHECK(file_size BETWEEN 0 AND 26214400),created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX inspection_attachments_request_idx ON public.inspection_request_attachments(inspection_request_id,created_at);
ALTER TABLE public.inspection_request_attachments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.inspection_request_attachments FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.inspection_request_attachments TO authenticated;GRANT ALL ON public.inspection_request_attachments TO service_role;
CREATE POLICY inspection_attachments_read ON public.inspection_request_attachments FOR SELECT TO authenticated USING(public.can_read_inspection_request(inspection_request_id));
CREATE POLICY inspection_files_upload ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id='inspection-attachments' AND (storage.foldername(name))[2]=auth.uid()::text
 AND EXISTS(SELECT 1 FROM public.inspection_requests r WHERE r.id::text=(storage.foldername(name))[1] AND r.status NOT IN ('proposal_requested','cancelled') AND public.can_edit_inspection_request(r.id)));
CREATE POLICY inspection_files_read ON storage.objects FOR SELECT TO authenticated USING(bucket_id='inspection-attachments'
 AND EXISTS(SELECT 1 FROM public.inspection_request_attachments a WHERE a.storage_path=name AND public.can_read_inspection_request(a.inspection_request_id)));
CREATE FUNCTION public.register_inspection_attachment(p_inspection_request_id uuid,p_id uuid,p_storage_path text,p_file_name text,p_file_size bigint)
RETURNS public.inspection_request_attachments LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE saved public.inspection_request_attachments;actual_size bigint;
BEGIN
 IF NOT public.can_edit_inspection_request(p_inspection_request_id) THEN RAISE EXCEPTION 'Request access required'; END IF;
 PERFORM 1 FROM public.inspection_requests WHERE id=p_inspection_request_id FOR UPDATE;
 IF EXISTS(SELECT 1 FROM public.inspection_requests WHERE id=p_inspection_request_id AND status IN ('proposal_requested','cancelled')) THEN RAISE EXCEPTION 'This inspection is closed for attachments'; END IF;
 IF p_id IS NULL OR p_storage_path IS NULL OR p_file_name IS NULL OR p_file_size IS NULL OR length(p_file_name) NOT BETWEEN 1 AND 255 OR p_file_size NOT BETWEEN 0 AND 26214400
 OR p_file_name !~* '\.(jpg|jpeg|png|webp|heic|heif|pdf|doc|docx|xls|xlsx|csv|txt)$'
 OR p_storage_path !~ ('^'||p_inspection_request_id::text||'/'||auth.uid()::text||'/'||p_id::text||'\.(jpg|jpeg|png|webp|heic|heif|pdf|doc|docx|xls|xlsx|csv|txt)$') THEN RAISE EXCEPTION 'Invalid attachment'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_id::text,0));
 SELECT * INTO saved FROM public.inspection_request_attachments WHERE id=p_id;
 IF FOUND THEN
 IF saved.inspection_request_id<>p_inspection_request_id OR saved.uploaded_by<>auth.uid() OR saved.storage_path<>p_storage_path OR saved.file_name<>p_file_name OR saved.file_size<>p_file_size THEN RAISE EXCEPTION 'Attachment ID already used'; END IF;RETURN saved;END IF;
 SELECT (metadata->>'size')::bigint INTO actual_size FROM storage.objects WHERE bucket_id='inspection-attachments' AND name=p_storage_path;
 IF actual_size IS NULL OR actual_size<>p_file_size THEN RAISE EXCEPTION 'Upload not confirmed; retry the file'; END IF;
 INSERT INTO public.inspection_request_attachments(id,inspection_request_id,uploaded_by,storage_path,file_name,file_size) VALUES(p_id,p_inspection_request_id,auth.uid(),p_storage_path,p_file_name,p_file_size) RETURNING * INTO saved;
 INSERT INTO public.inspection_request_audit(inspection_request_id,actor_id,action,details) VALUES(p_inspection_request_id,auth.uid(),'attachment_added',jsonb_build_object('file_name',p_file_name,'attachment_id',p_id));
 RETURN saved;
END;$$;

CREATE FUNCTION public.create_inspection_proposal_request(p_id uuid,p_expected_version integer)
RETURNS public.inspection_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE r public.inspection_requests;p public.proposal_requests;
BEGIN
 SELECT * INTO r FROM public.inspection_requests WHERE id=p_id FOR UPDATE;
 IF NOT FOUND OR NOT public.can_edit_inspection_request(p_id) OR (r.assigned_to IS DISTINCT FROM auth.uid() AND NOT public.is_proposal_manager()) THEN RAISE EXCEPTION 'Assigned technician or office access required'; END IF;
 IF r.proposal_request_id IS NOT NULL THEN RETURN r; END IF;
 IF r.status<>'inspected' OR r.version IS DISTINCT FROM p_expected_version THEN RAISE EXCEPTION 'Save and confirm the inspection before creating its proposal request'; END IF;
 IF trim(r.findings)='' OR trim(r.measurements)='' OR trim(r.property_address)='' THEN RAISE EXCEPTION 'Inspection findings, measurements and property address are required for the proposal handoff'; END IF;
 -- Guarded handoff reuses the existing proposal intake and Daniela review gate.
 -- Only the assigned inspector or office may create it; missing pricing is never invented.
 INSERT INTO public.proposal_requests(created_by,salesperson_id,customer_name,property_name,service_address,project_contact_phone,project_contact_email,
 existing_lead_job_id,scope_of_work,measurements,salesperson_notes,priority)
 VALUES(auth.uid(),r.assigned_to,r.contact_name,r.contact_name,r.property_address,r.phone,r.email,coalesce(r.lead_id::text,''),r.findings,r.measurements,r.notes,
 CASE WHEN r.urgency IN ('High','Urgent') THEN 'high' ELSE 'normal' END) RETURNING * INTO p;
 PERFORM public.write_proposal_audit(p.id,'created','Created from inspection request IR-'||r.request_number);
 PERFORM public.submit_draft_proposal_handoff(p.id,false);
 UPDATE public.inspection_requests SET proposal_request_id=p.id,status='proposal_requested',updated_at=now(),version=version+1 WHERE id=p_id RETURNING * INTO r;
 RETURN r;
END;$$;
REVOKE ALL ON FUNCTION public.save_inspection_request(uuid,jsonb,integer),public.submit_inspection_request(uuid,integer),public.transition_inspection_request(uuid,text,integer),public.register_inspection_attachment(uuid,uuid,text,text,bigint),public.create_inspection_proposal_request(uuid,integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.save_inspection_request(uuid,jsonb,integer),public.submit_inspection_request(uuid,integer),public.transition_inspection_request(uuid,text,integer),public.register_inspection_attachment(uuid,uuid,text,text,bigint),public.create_inspection_proposal_request(uuid,integer) TO authenticated;
CREATE FUNCTION public.capture_crm_inspection_request() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE lead public.crm_leads;t public.company_tasks;technician uuid;
BEGIN
 IF EXISTS(SELECT 1 FROM public.inspection_requests WHERE lead_id=NEW.lead_id AND created_by=NEW.requested_by) THEN RETURN NEW; END IF;
 SELECT * INTO lead FROM public.crm_leads WHERE id=NEW.lead_id;
 SELECT * INTO t FROM public.company_tasks WHERE id=NEW.task_id;
 SELECT user_id INTO technician FROM public.company_task_assignees WHERE task_id=t.id ORDER BY assigned_at LIMIT 1;
 INSERT INTO public.inspection_requests(created_by,assigned_to,lead_id,task_id,status,contact_name,phone,email,property_address,notes,urgency,submitted_at)
 VALUES(NEW.requested_by,technician,lead.id,t.id,'new',coalesce(nullif(lead.contact_name,''),nullif(lead.company_name,''),lead.first_name||' '||lead.last_name),lead.phone,lead.email,lead.property_address,lead.quick_note,CASE WHEN t.priority IN ('high','urgent') THEN 'High' ELSE 'Normal' END,t.created_at);
 RETURN NEW;
END;$$;
REVOKE ALL ON FUNCTION public.capture_crm_inspection_request() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER capture_crm_inspection_request AFTER INSERT ON public.inspection_request_tasks FOR EACH ROW EXECUTE FUNCTION public.capture_crm_inspection_request();

COMMIT;
