-- Secure liquid-cash email-code reveal (apply manually; do not expose cash via RLS)
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.liquid_cash_access_challenges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 5),
  max_attempts integer NOT NULL DEFAULT 5 CHECK (max_attempts = 5),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'expired', 'exhausted', 'superseded', 'email_failed')),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  verified_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_liquid_cash_challenges_user_created
  ON public.liquid_cash_access_challenges(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.liquid_cash_reveal_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL REFERENCES public.liquid_cash_access_challenges(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  expires_at timestamptz NOT NULL,
  revealed_at timestamptz,
  hidden_at timestamptz,
  hide_reason text CHECK (hide_reason IS NULL OR hide_reason IN ('hidden', 'expired'))
);

CREATE INDEX IF NOT EXISTS idx_liquid_cash_reveal_user_expiry
  ON public.liquid_cash_reveal_sessions(user_id, expires_at DESC);

CREATE TABLE IF NOT EXISTS public.liquid_cash_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  challenge_id uuid REFERENCES public.liquid_cash_access_challenges(id) ON DELETE SET NULL,
  reveal_session_id uuid REFERENCES public.liquid_cash_reveal_sessions(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  event_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_liquid_cash_audit_user_event
  ON public.liquid_cash_audit_events(user_id, event_at DESC);

ALTER TABLE public.liquid_cash_access_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liquid_cash_reveal_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liquid_cash_audit_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.liquid_cash_access_challenges FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.liquid_cash_reveal_sessions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.liquid_cash_audit_events FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.is_liquid_cash_access_user(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_profiles
    WHERE id = p_user_id
      AND role IN ('admin', 'cfo')
  );
$$;

REVOKE ALL ON FUNCTION public.is_liquid_cash_access_user(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_liquid_cash_access_user(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.verify_liquid_cash_challenge(
  p_challenge_id uuid,
  p_user_id uuid,
  p_code_hash text,
  p_reveal_token_hash text
)
RETURNS TABLE (
  outcome text,
  attempts_remaining integer,
  reveal_session_id uuid,
  reveal_expires_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  challenge_row public.liquid_cash_access_challenges%ROWTYPE;
  next_attempt_count integer;
  new_session_id uuid;
  new_expiry timestamptz;
BEGIN
  SELECT * INTO challenge_row
  FROM public.liquid_cash_access_challenges
  WHERE id = p_challenge_id AND user_id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN QUERY SELECT 'invalid'::text, 0, NULL::uuid, NULL::timestamptz;
    RETURN;
  END IF;

  IF challenge_row.status <> 'pending' THEN
    RETURN QUERY SELECT
      CASE WHEN challenge_row.status = 'verified' THEN 'already_used' ELSE challenge_row.status END,
      0,
      NULL::uuid,
      NULL::timestamptz;
    RETURN;
  END IF;

  IF clock_timestamp() >= challenge_row.expires_at THEN
    UPDATE public.liquid_cash_access_challenges SET status = 'expired' WHERE id = challenge_row.id;
    INSERT INTO public.liquid_cash_audit_events(user_id, challenge_id, event_type, metadata)
    VALUES (p_user_id, challenge_row.id, 'code_expired', jsonb_build_object('expires_at', challenge_row.expires_at));
    RETURN QUERY SELECT 'expired'::text, 0, NULL::uuid, NULL::timestamptz;
    RETURN;
  END IF;

  IF challenge_row.attempt_count >= challenge_row.max_attempts THEN
    UPDATE public.liquid_cash_access_challenges SET status = 'exhausted' WHERE id = challenge_row.id;
    RETURN QUERY SELECT 'exhausted'::text, 0, NULL::uuid, NULL::timestamptz;
    RETURN;
  END IF;

  IF challenge_row.code_hash <> p_code_hash THEN
    next_attempt_count := challenge_row.attempt_count + 1;
    UPDATE public.liquid_cash_access_challenges
    SET attempt_count = next_attempt_count,
        status = CASE WHEN next_attempt_count >= max_attempts THEN 'exhausted' ELSE 'pending' END
    WHERE id = challenge_row.id;
    INSERT INTO public.liquid_cash_audit_events(user_id, challenge_id, event_type, metadata)
    VALUES (
      p_user_id,
      challenge_row.id,
      CASE WHEN next_attempt_count >= challenge_row.max_attempts THEN 'attempts_exhausted' ELSE 'verification_failed' END,
      jsonb_build_object('attempt_number', next_attempt_count, 'attempts_remaining', GREATEST(0, challenge_row.max_attempts - next_attempt_count))
    );
    RETURN QUERY SELECT
      CASE WHEN next_attempt_count >= challenge_row.max_attempts THEN 'exhausted' ELSE 'failed' END,
      GREATEST(0, challenge_row.max_attempts - next_attempt_count),
      NULL::uuid,
      NULL::timestamptz;
    RETURN;
  END IF;

  UPDATE public.liquid_cash_access_challenges
  SET status = 'verified', verified_at = clock_timestamp()
  WHERE id = challenge_row.id;
  INSERT INTO public.liquid_cash_audit_events(user_id, challenge_id, event_type, metadata)
  VALUES (p_user_id, challenge_row.id, 'verification_succeeded', '{}'::jsonb);

  new_session_id := gen_random_uuid();
  new_expiry := clock_timestamp() + interval '60 seconds';
  INSERT INTO public.liquid_cash_reveal_sessions(id, challenge_id, user_id, token_hash, expires_at)
  VALUES (new_session_id, challenge_row.id, p_user_id, p_reveal_token_hash, new_expiry);
  INSERT INTO public.liquid_cash_audit_events(user_id, challenge_id, reveal_session_id, event_type, metadata)
  VALUES (p_user_id, challenge_row.id, new_session_id, 'reveal_started', jsonb_build_object('expires_at', new_expiry));

  RETURN QUERY SELECT 'success'::text, challenge_row.max_attempts - challenge_row.attempt_count, new_session_id, new_expiry;
END;
$$;

REVOKE ALL ON FUNCTION public.verify_liquid_cash_challenge(uuid, uuid, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_liquid_cash_challenge(uuid, uuid, text, text) TO service_role;

DROP POLICY IF EXISTS company_financial_records_select_finance ON public.company_financial_records;
DROP POLICY IF EXISTS company_financial_records_insert_finance ON public.company_financial_records;
DROP POLICY IF EXISTS company_financial_records_update_finance ON public.company_financial_records;

CREATE POLICY company_financial_records_select_finance
  ON public.company_financial_records
  FOR SELECT TO authenticated
  USING (public.is_finance_user() AND record_type <> 'liquid_cash');

CREATE POLICY company_financial_records_insert_finance
  ON public.company_financial_records
  FOR INSERT TO authenticated
  WITH CHECK (public.is_finance_user() AND record_type <> 'liquid_cash');

CREATE POLICY company_financial_records_update_finance
  ON public.company_financial_records
  FOR UPDATE TO authenticated
  USING (public.is_finance_user() AND record_type <> 'liquid_cash')
  WITH CHECK (public.is_finance_user() AND record_type <> 'liquid_cash');

COMMIT;
