BEGIN;

CREATE TABLE IF NOT EXISTS public.credential_vault_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  website_name text NOT NULL,
  website_url text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'Other',
  encrypted_secret text NOT NULL,
  encryption_iv text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid NOT NULL REFERENCES public.user_profiles(id),
  updated_by uuid NOT NULL REFERENCES public.user_profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.credential_access_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  request_type text NOT NULL CHECK (request_type IN ('catalog', 'item')),
  catalog_request_id uuid REFERENCES public.credential_access_requests(id) ON DELETE CASCADE,
  vault_entry_id uuid REFERENCES public.credential_vault_entries(id) ON DELETE CASCADE,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'denied', 'expired', 'revoked')),
  approved_by uuid REFERENCES public.user_profiles(id),
  approved_at timestamptz,
  expires_at timestamptz,
  revealed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (request_type = 'catalog' AND catalog_request_id IS NULL AND vault_entry_id IS NULL)
    OR (request_type = 'item' AND catalog_request_id IS NOT NULL AND vault_entry_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS credential_access_requester_idx
  ON public.credential_access_requests(requester_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS credential_access_pending_idx
  ON public.credential_access_requests(status, request_type, created_at DESC);

CREATE TABLE IF NOT EXISTS public.credential_access_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  requester_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  request_id uuid REFERENCES public.credential_access_requests(id) ON DELETE SET NULL,
  vault_entry_id uuid REFERENCES public.credential_vault_entries(id) ON DELETE SET NULL,
  action text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.credential_vault_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credential_access_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credential_access_audit_log ENABLE ROW LEVEL SECURITY;

-- Secrets and requests are available only through the authenticated Edge Function.
-- Even authenticated browser sessions cannot query ciphertext, request rows, or audit rows.
REVOKE ALL ON TABLE public.credential_vault_entries FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.credential_access_requests FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.credential_access_audit_log FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.credential_vault_entries TO service_role;
GRANT ALL ON TABLE public.credential_access_requests TO service_role;
GRANT ALL ON TABLE public.credential_access_audit_log TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.credential_access_audit_log_id_seq TO service_role;

COMMIT;
