-- Centralized proposal request, authorization, and production-release workflow.
-- Client code cannot write these records directly; guarded RPCs below enforce transitions.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.current_company_role()
RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT lower(coalesce((SELECT role FROM public.user_profiles WHERE id = auth.uid()), ''));
$$;

CREATE OR REPLACE FUNCTION public.is_proposal_manager()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT public.current_company_role() IN ('admin', 'cfo');
$$;

CREATE OR REPLACE FUNCTION public.is_company_estimator()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT public.current_company_role() = 'estimator'
    OR lower(coalesce((SELECT email FROM public.user_profiles WHERE id = auth.uid()), auth.jwt() ->> 'email', '')) = 'daniela@crtroofing.com';
$$;

REVOKE ALL ON FUNCTION public.current_company_role(), public.is_proposal_manager(), public.is_company_estimator() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.current_company_role(), public.is_proposal_manager(), public.is_company_estimator() TO authenticated;

ALTER TABLE public.company_tasks ADD COLUMN IF NOT EXISTS task_type text NOT NULL DEFAULT 'general';
ALTER TABLE public.company_tasks DROP CONSTRAINT IF EXISTS company_tasks_task_type_check;
ALTER TABLE public.company_tasks ADD CONSTRAINT company_tasks_task_type_check CHECK (task_type IN ('general', 'proposal_request'));

ALTER TABLE public.active_jobs ADD COLUMN IF NOT EXISTS proposal_request_id uuid;
ALTER TABLE public.active_jobs ADD COLUMN IF NOT EXISTS production_authorized_at timestamptz;
ALTER TABLE public.active_jobs ADD COLUMN IF NOT EXISTS production_authorized_by uuid;
ALTER TABLE public.active_jobs ADD COLUMN IF NOT EXISTS production_authorization_source text NOT NULL DEFAULT '';

CREATE TABLE public.proposal_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid UNIQUE REFERENCES public.company_tasks(id) ON DELETE SET NULL,
  request_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','under_review','missing_information','drafting_proposal','sales_review','ready_to_send','sent','signed','declined','closed')),
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal','high','rush')),
  rush_approval_status text NOT NULL DEFAULT 'not_required' CHECK (rush_approval_status IN ('not_required','pending','approved','rejected')),
  rush_approved_by uuid REFERENCES public.user_profiles(id), rush_approved_at timestamptz,
  created_by uuid NOT NULL REFERENCES public.user_profiles(id) DEFAULT auth.uid(),
  salesperson_id uuid NOT NULL REFERENCES public.user_profiles(id),
  assigned_estimator_id uuid REFERENCES public.user_profiles(id),
  existing_lead_job_id text NOT NULL DEFAULT '',
  customer_name text NOT NULL DEFAULT '', property_name text NOT NULL DEFAULT '', service_address text NOT NULL DEFAULT '',
  billing_information text NOT NULL DEFAULT '', customer_contact text NOT NULL DEFAULT '',
  project_contact_first_name text NOT NULL DEFAULT '', project_contact_last_name text NOT NULL DEFAULT '',
  project_contact_phone text NOT NULL DEFAULT '', project_contact_email text NOT NULL DEFAULT '',
  job_type text NOT NULL DEFAULT 'standard_roof' CHECK (job_type IN ('minor_repair','standard_roof','complex_commercial','large_rfp')),
  scope_of_work text NOT NULL DEFAULT '', roof_areas text NOT NULL DEFAULT '', roofing_system text NOT NULL DEFAULT '', work_type text NOT NULL DEFAULT '',
  measurements text NOT NULL DEFAULT '', roof_measurement_notes text NOT NULL DEFAULT '', total_linear_feet numeric,
  property_type text NOT NULL DEFAULT '', story_count text NOT NULL DEFAULT '', construction_type text NOT NULL DEFAULT '',
  material_specifications text NOT NULL DEFAULT '', existing_layers text NOT NULL DEFAULT '', warranty_requirements text NOT NULL DEFAULT '',
  tear_off_details text NOT NULL DEFAULT '', parapet_wall_measurements text NOT NULL DEFAULT '', ac_work_details text NOT NULL DEFAULT '',
  plywood_fascia_notes text NOT NULL DEFAULT '', detail_component_notes text NOT NULL DEFAULT '', accessories_needed text NOT NULL DEFAULT '',
  deck_material_requirements text NOT NULL DEFAULT '', shingle_selection text NOT NULL DEFAULT '', tile_selection text NOT NULL DEFAULT '',
  warranty_upgrade_options text NOT NULL DEFAULT '', subcontractor_requirements text NOT NULL DEFAULT '', roof_access_details text NOT NULL DEFAULT '',
  permit_requirements text NOT NULL DEFAULT '', weekend_work_availability text NOT NULL DEFAULT '', overspray_risk_notes text NOT NULL DEFAULT '',
  parking_zone_sign_locations text NOT NULL DEFAULT '',
  special_conditions text NOT NULL DEFAULT '', exclusions text NOT NULL DEFAULT '', allowances text NOT NULL DEFAULT '', alternates text NOT NULL DEFAULT '',
  estimated_crew_size numeric, estimated_working_days numeric,
  equipment_requirements text NOT NULL DEFAULT '', crane_requirements text NOT NULL DEFAULT '', hvac_requirements text NOT NULL DEFAULT '',
  travel_lodging text NOT NULL DEFAULT '', production_notes text NOT NULL DEFAULT '',
  estimated_material_quantities text NOT NULL DEFAULT '', estimated_labor_assumptions text NOT NULL DEFAULT '', target_price numeric,
  pricing_notes text NOT NULL DEFAULT '', margin_markup_assumptions text NOT NULL DEFAULT '', payment_deposit_terms text NOT NULL DEFAULT '',
  deposit_required boolean NOT NULL DEFAULT false, deposit_satisfied_at timestamptz, deposit_satisfied_by uuid REFERENCES public.user_profiles(id),
  customer_requests text NOT NULL DEFAULT '', verbal_commitments text NOT NULL DEFAULT '', customer_deadline date, salesperson_notes text NOT NULL DEFAULT '',
  missing_information_notes text NOT NULL DEFAULT '', missing_information_count integer NOT NULL DEFAULT 0,
  submitted_at timestamptz, accepted_at timestamptz, target_completion_at timestamptz, manual_target_at timestamptz,
  sla_paused_at timestamptz, sla_paused_seconds bigint NOT NULL DEFAULT 0,
  sent_at timestamptz, signed_at timestamptz, declined_at timestamptz, closed_at timestamptz,
  production_scope jsonb NOT NULL DEFAULT '{"authorized":[],"not_authorized":[]}'::jsonb,
  production_scope_generated_at timestamptz, production_released_at timestamptz, production_released_by uuid REFERENCES public.user_profiles(id),
  production_override_reason text NOT NULL DEFAULT '', active_job_id uuid REFERENCES public.active_jobs(id),
  production_started_without_authorization boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.active_jobs ADD CONSTRAINT active_jobs_proposal_request_fk
FOREIGN KEY (proposal_request_id) REFERENCES public.proposal_requests(id) ON DELETE SET NULL;

CREATE TABLE public.proposal_request_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), proposal_request_id uuid NOT NULL REFERENCES public.proposal_requests(id) ON DELETE CASCADE,
  category text NOT NULL CHECK (category IN ('photo','measurement','roof_report','drawing','rfp','customer_document','other')),
  file_name text NOT NULL, storage_path text NOT NULL UNIQUE, content_type text NOT NULL DEFAULT '', file_size bigint NOT NULL DEFAULT 0 CHECK (file_size >= 0),
  uploaded_by uuid NOT NULL REFERENCES public.user_profiles(id) DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.proposal_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), proposal_request_id uuid NOT NULL REFERENCES public.proposal_requests(id) ON DELETE CASCADE,
  version_number integer NOT NULL CHECK (version_number > 0), proposal_id text NOT NULL DEFAULT '', estimate_id text NOT NULL DEFAULT '',
  pdf_storage_path text NOT NULL DEFAULT '', sections jsonb NOT NULL DEFAULT '[]'::jsonb,
  finalized_at timestamptz, finalized_by uuid REFERENCES public.user_profiles(id),
  sales_approved_at timestamptz, sales_approved_by uuid REFERENCES public.user_profiles(id), sales_acknowledgement text NOT NULL DEFAULT '',
  customer_decision text NOT NULL DEFAULT 'pending' CHECK (customer_decision IN ('pending','signed','declined')),
  customer_name text NOT NULL DEFAULT '', customer_signature_storage_path text NOT NULL DEFAULT '',
  customer_signed_at timestamptz, customer_declined_at timestamptz, sent_at timestamptz, viewed_at timestamptz,
  created_by uuid NOT NULL REFERENCES public.user_profiles(id) DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (proposal_request_id, version_number)
);

CREATE TABLE public.proposal_signing_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_version_id uuid NOT NULL REFERENCES public.proposal_versions(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_by uuid NOT NULL REFERENCES public.user_profiles(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.proposal_change_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), proposal_request_id uuid NOT NULL REFERENCES public.proposal_requests(id) ON DELETE CASCADE,
  description text NOT NULL CHECK (length(trim(description)) > 0), scope text NOT NULL CHECK (length(trim(scope)) > 0),
  price numeric NOT NULL DEFAULT 0 CHECK (price >= 0), status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','signed','declined','void')),
  required_for_release boolean NOT NULL DEFAULT true, customer_signature_storage_path text NOT NULL DEFAULT '', customer_signed_at timestamptz,
  created_by uuid NOT NULL REFERENCES public.user_profiles(id) DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.proposal_change_order_signing_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  change_order_id uuid NOT NULL REFERENCES public.proposal_change_orders(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_by uuid NOT NULL REFERENCES public.user_profiles(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.proposal_request_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, proposal_request_id uuid NOT NULL REFERENCES public.proposal_requests(id) ON DELETE CASCADE,
  actor_id uuid REFERENCES public.user_profiles(id), action text NOT NULL, notes text NOT NULL DEFAULT '',
  proposal_version_id uuid REFERENCES public.proposal_versions(id) ON DELETE SET NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.proposal_request_notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), proposal_request_id uuid NOT NULL REFERENCES public.proposal_requests(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE, actor_id uuid REFERENCES public.user_profiles(id),
  notification_type text NOT NULL, message text NOT NULL, read_at timestamptz,
  email_status text NOT NULL DEFAULT 'pending' CHECK (email_status IN ('pending','sent','failed','skipped')),
  email_sent_at timestamptz, email_error text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX proposal_requests_queue_idx ON public.proposal_requests(status,target_completion_at,priority);
CREATE INDEX proposal_requests_salesperson_idx ON public.proposal_requests(salesperson_id,created_at DESC);
CREATE INDEX proposal_requests_estimator_idx ON public.proposal_requests(assigned_estimator_id,created_at DESC);
CREATE INDEX proposal_audit_request_idx ON public.proposal_request_audit_events(proposal_request_id,created_at DESC);
CREATE INDEX proposal_notifications_user_idx ON public.proposal_request_notifications(user_id,created_at DESC);

CREATE OR REPLACE FUNCTION public.can_access_proposal_request(request_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT EXISTS (SELECT 1 FROM public.proposal_requests request WHERE request.id=request_id AND (
    request.created_by=auth.uid() OR request.salesperson_id=auth.uid() OR request.assigned_estimator_id=auth.uid()
    OR public.is_company_estimator() OR public.is_proposal_manager()));
$$;
REVOKE ALL ON FUNCTION public.can_access_proposal_request(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_access_proposal_request(uuid) TO authenticated;

ALTER TABLE public.proposal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_request_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_signing_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_change_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_change_order_signing_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_request_audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_request_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY proposal_requests_select_participants ON public.proposal_requests FOR SELECT TO authenticated USING (public.can_access_proposal_request(id));
CREATE POLICY proposal_attachments_select_participants ON public.proposal_request_attachments FOR SELECT TO authenticated USING (public.can_access_proposal_request(proposal_request_id));
CREATE POLICY proposal_versions_select_participants ON public.proposal_versions FOR SELECT TO authenticated USING (public.can_access_proposal_request(proposal_request_id));
CREATE POLICY proposal_signing_sessions_select_creator ON public.proposal_signing_sessions FOR SELECT TO authenticated USING (created_by=auth.uid() OR public.is_proposal_manager());
CREATE POLICY proposal_change_orders_select_participants ON public.proposal_change_orders FOR SELECT TO authenticated USING (public.can_access_proposal_request(proposal_request_id));
CREATE POLICY proposal_change_order_sessions_select_creator ON public.proposal_change_order_signing_sessions FOR SELECT TO authenticated USING (created_by=auth.uid() OR public.is_proposal_manager());
CREATE POLICY proposal_audit_select_participants ON public.proposal_request_audit_events FOR SELECT TO authenticated USING (public.can_access_proposal_request(proposal_request_id));
CREATE POLICY proposal_notifications_select_self ON public.proposal_request_notifications FOR SELECT TO authenticated USING (user_id=auth.uid());
CREATE POLICY proposal_notifications_read_self ON public.proposal_request_notifications FOR UPDATE TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());

CREATE OR REPLACE FUNCTION public.proposal_request_required_missing(payload jsonb)
RETURNS text[] LANGUAGE sql IMMUTABLE AS $$
  SELECT array_remove(ARRAY[
    CASE WHEN trim(coalesce(payload->>'customer_name',''))='' THEN 'Customer name' END,
    CASE WHEN trim(coalesce(payload->>'property_name',''))='' THEN 'Property / job name' END,
    CASE WHEN trim(coalesce(payload->>'service_address',''))='' THEN 'Property service address' END,
    CASE WHEN trim(coalesce(payload->>'billing_information',''))='' THEN 'Billing information' END,
    CASE WHEN trim(coalesce(payload->>'project_contact_first_name',''))='' THEN 'Project contact first name' END,
    CASE WHEN trim(coalesce(payload->>'project_contact_last_name',''))='' THEN 'Project contact last name' END,
    CASE WHEN trim(coalesce(payload->>'project_contact_phone',''))='' THEN 'Project contact phone number' END,
    CASE WHEN trim(coalesce(payload->>'project_contact_email',''))='' THEN 'Project contact email' END,
    CASE WHEN trim(coalesce(payload->>'scope_of_work',''))='' THEN 'Detailed scope of work' END,
    CASE WHEN trim(coalesce(payload->>'roof_areas',''))='' THEN 'Roof areas / sections' END,
    CASE WHEN trim(coalesce(payload->>'roofing_system',''))='' THEN 'Roofing system' END,
    CASE WHEN trim(coalesce(payload->>'work_type',''))='' THEN 'Work type' END,
    CASE WHEN trim(coalesce(payload->>'measurements',''))='' THEN 'Measurements' END,
    CASE WHEN trim(coalesce(payload->>'roof_measurement_notes',''))='' THEN 'Roof measurement notes' END,
    CASE WHEN trim(coalesce(payload->>'property_type',''))='' THEN 'Property type' END,
    CASE WHEN trim(coalesce(payload->>'story_count',''))='' THEN 'Building story count' END,
    CASE WHEN trim(coalesce(payload->>'construction_type',''))='' THEN 'Existing roof or new construction' END,
    CASE WHEN trim(coalesce(payload->>'material_specifications',''))='' THEN 'Material specifications' END,
    CASE WHEN coalesce((payload->>'estimated_crew_size')::numeric,0)<=0 THEN 'Estimated crew size' END,
    CASE WHEN coalesce((payload->>'estimated_working_days')::numeric,0)<=0 THEN 'Estimated working days' END,
    CASE WHEN trim(coalesce(payload->>'estimated_material_quantities',''))='' THEN 'Estimated material quantities' END,
    CASE WHEN trim(coalesce(payload->>'estimated_labor_assumptions',''))='' THEN 'Estimated labor assumptions' END,
    CASE WHEN trim(coalesce(payload->>'customer_deadline',''))='' THEN 'Customer deadline' END,
    CASE WHEN payload->>'job_type'='large_rfp' AND trim(coalesce(payload->>'manual_target_at',''))='' THEN 'Manual ETA' END
  ],NULL);
$$;

CREATE OR REPLACE FUNCTION public.add_proposal_business_days(start_at timestamptz,day_count integer)
RETURNS timestamptz LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE result timestamptz:=start_at; remaining integer:=greatest(day_count,0);
BEGIN
  WHILE remaining>0 LOOP
    result:=result+interval '1 day';
    IF extract(isodow FROM result)<6 THEN remaining:=remaining-1; END IF;
  END LOOP;
  RETURN result;
END;
$$;

-- Internal helpers are revoked from browser roles; guarded workflow functions call them.
CREATE OR REPLACE FUNCTION public.write_proposal_audit(request_id uuid,action_name text,note_text text DEFAULT '',version_id uuid DEFAULT NULL,event_metadata jsonb DEFAULT '{}'::jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  INSERT INTO public.proposal_request_audit_events(proposal_request_id,actor_id,action,notes,proposal_version_id,metadata)
  VALUES(request_id,auth.uid(),action_name,coalesce(note_text,''),version_id,coalesce(event_metadata,'{}'::jsonb));
END;
$$;

CREATE OR REPLACE FUNCTION public.queue_proposal_notification(request_id uuid,recipient_id uuid,kind text,body text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF recipient_id IS NOT NULL AND recipient_id<>auth.uid() THEN
    INSERT INTO public.proposal_request_notifications(proposal_request_id,user_id,actor_id,notification_type,message)
    VALUES(request_id,recipient_id,auth.uid(),kind,body);
  END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.write_proposal_audit(uuid,text,text,uuid,jsonb),public.queue_proposal_notification(uuid,uuid,text,text) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.save_proposal_version(p_request_id uuid,p_sections jsonb,p_proposal_id text DEFAULT '',p_estimate_id text DEFAULT '',p_pdf_storage_path text DEFAULT '',p_finalize boolean DEFAULT false)
RETURNS public.proposal_versions LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE version public.proposal_versions; next_number integer;
BEGIN
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager()) OR NOT public.can_access_proposal_request(p_request_id) THEN RAISE EXCEPTION 'Estimator access required'; END IF;
  IF jsonb_typeof(p_sections)<>'array' OR jsonb_array_length(p_sections)=0 THEN RAISE EXCEPTION 'At least one proposal section is required'; END IF;
  SELECT coalesce(max(version_number),0)+1 INTO next_number FROM public.proposal_versions WHERE proposal_request_id=p_request_id;
  INSERT INTO public.proposal_versions(proposal_request_id,version_number,proposal_id,estimate_id,pdf_storage_path,sections,finalized_at,finalized_by)
  VALUES(p_request_id,next_number,coalesce(p_proposal_id,''),coalesce(p_estimate_id,''),coalesce(p_pdf_storage_path,''),p_sections,CASE WHEN p_finalize THEN now() END,CASE WHEN p_finalize THEN auth.uid() END) RETURNING * INTO version;
  UPDATE public.proposal_requests SET status=CASE WHEN p_finalize THEN 'sales_review' ELSE 'drafting_proposal' END,updated_at=now() WHERE id=p_request_id;
  PERFORM public.queue_proposal_notification(p_request_id,(SELECT salesperson_id FROM public.proposal_requests WHERE id=p_request_id),'sales_review',CASE WHEN p_finalize THEN 'Proposal is ready for Sales Review.' ELSE 'A proposal draft was created.' END);
  PERFORM public.write_proposal_audit(p_request_id,CASE WHEN p_finalize THEN 'proposal_finalized' ELSE 'proposal_drafted' END,'Version '||next_number,version.id); RETURN version;
END;
$$;

CREATE OR REPLACE FUNCTION public.approve_proposal_scope(p_version_id uuid,p_acknowledgement text)
RETURNS public.proposal_versions LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE version public.proposal_versions; request public.proposal_requests;
BEGIN
  SELECT * INTO version FROM public.proposal_versions WHERE id=p_version_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Proposal version not found'; END IF;
  SELECT * INTO request FROM public.proposal_requests WHERE id=version.proposal_request_id FOR UPDATE;
  IF request.salesperson_id<>auth.uid() AND NOT public.is_proposal_manager() THEN RAISE EXCEPTION 'Assigned salesperson approval required'; END IF;
  IF version.finalized_at IS NULL THEN RAISE EXCEPTION 'Proposal version is not finalized'; END IF;
  IF trim(coalesce(p_acknowledgement,'')) NOT LIKE 'I confirm that the scope,%' THEN RAISE EXCEPTION 'Scope acknowledgement is required'; END IF;
  UPDATE public.proposal_versions SET sales_approved_at=now(),sales_approved_by=auth.uid(),sales_acknowledgement=p_acknowledgement,updated_at=now() WHERE id=p_version_id RETURNING * INTO version;
  UPDATE public.proposal_requests SET status='ready_to_send',updated_at=now() WHERE id=request.id;
  PERFORM public.queue_proposal_notification(request.id,request.assigned_estimator_id,'sales_approved','Sales approved proposal version '||version.version_number||'.');
  PERFORM public.write_proposal_audit(request.id,'salesperson_approved',p_acknowledgement,version.id); RETURN version;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_proposal_signing_session(p_version_id uuid,p_expires_hours integer DEFAULT 168)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE version public.proposal_versions; raw_token text:=encode(gen_random_bytes(32),'hex'); session_id uuid; expiry timestamptz;
BEGIN
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager()) THEN RAISE EXCEPTION 'Estimator or management access required'; END IF;
  SELECT * INTO version FROM public.proposal_versions WHERE id=p_version_id;
  IF NOT FOUND OR NOT public.can_access_proposal_request(version.proposal_request_id) THEN RAISE EXCEPTION 'Proposal version not found'; END IF;
  IF version.sales_approved_at IS NULL THEN RAISE EXCEPTION 'Salesperson approval is required before sending'; END IF;
  expiry:=now()+make_interval(hours=>least(greatest(p_expires_hours,1),720));
  INSERT INTO public.proposal_signing_sessions(proposal_version_id,token_hash,expires_at,created_by)
  VALUES(version.id,encode(digest(raw_token,'sha256'),'hex'),expiry,auth.uid()) RETURNING id INTO session_id;
  UPDATE public.proposal_versions SET sent_at=coalesce(sent_at,now()),updated_at=now() WHERE id=version.id;
  UPDATE public.proposal_requests SET status='sent',sent_at=coalesce(sent_at,now()),updated_at=now() WHERE id=version.proposal_request_id;
  PERFORM public.write_proposal_audit(version.proposal_request_id,'proposal_sent','Secure signing link created',version.id,jsonb_build_object('signing_session_id',session_id,'expires_at',expiry));
  RETURN jsonb_build_object('token',raw_token,'expires_at',expiry,'proposal_version_id',version.id);
END;
$$;

-- Called only by the execute-proposal Edge Function with the service role after
-- validating the one-time token. Authenticated clients cannot execute it.
CREATE OR REPLACE FUNCTION public.complete_customer_proposal_decision(p_raw_token text,p_decision text,p_customer_name text,p_signature_path text,p_approved_section_ids text[] DEFAULT '{}')
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE session public.proposal_signing_sessions; version public.proposal_versions; request public.proposal_requests; selected_sections jsonb;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Service role required'; END IF;
  SELECT * INTO session FROM public.proposal_signing_sessions WHERE token_hash=encode(digest(p_raw_token,'sha256'),'hex') AND used_at IS NULL AND expires_at>now() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Signing link is invalid or expired'; END IF;
  SELECT * INTO version FROM public.proposal_versions WHERE id=session.proposal_version_id FOR UPDATE;
  SELECT * INTO request FROM public.proposal_requests WHERE id=version.proposal_request_id FOR UPDATE;
  IF p_decision='signed' THEN
    IF trim(coalesce(p_signature_path,''))='' OR cardinality(p_approved_section_ids)=0 THEN RAISE EXCEPTION 'Signature and approved sections are required'; END IF;
    SELECT coalesce(jsonb_agg(section),'[]'::jsonb) INTO selected_sections FROM jsonb_array_elements(version.sections) section WHERE section->>'id'=ANY(p_approved_section_ids);
    IF jsonb_array_length(selected_sections)<>cardinality(p_approved_section_ids) THEN RAISE EXCEPTION 'Unknown proposal section selected'; END IF;
    UPDATE public.proposal_versions SET sections=(SELECT jsonb_agg(section||jsonb_build_object('customer_approved',(section->>'id'=ANY(p_approved_section_ids)))) FROM jsonb_array_elements(version.sections) section),customer_decision='signed',customer_name=trim(p_customer_name),customer_signature_storage_path=trim(p_signature_path),customer_signed_at=now(),updated_at=now() WHERE id=version.id RETURNING * INTO version;
    UPDATE public.proposal_requests SET status='signed',signed_at=now(),production_scope=jsonb_build_object('authorized',(SELECT coalesce(jsonb_agg(s),'[]'::jsonb) FROM jsonb_array_elements(version.sections) s WHERE coalesce((s->>'customer_approved')::boolean,false)),'not_authorized',(SELECT coalesce(jsonb_agg(s),'[]'::jsonb) FROM jsonb_array_elements(version.sections) s WHERE NOT coalesce((s->>'customer_approved')::boolean,false))),production_scope_generated_at=now(),updated_at=now() WHERE id=request.id;
  ELSIF p_decision='declined' THEN
    UPDATE public.proposal_versions SET customer_decision='declined',customer_name=trim(p_customer_name),customer_declined_at=now(),updated_at=now() WHERE id=version.id;
    UPDATE public.proposal_requests SET status='declined',declined_at=now(),updated_at=now() WHERE id=request.id;
  ELSE RAISE EXCEPTION 'Invalid customer decision'; END IF;
  UPDATE public.proposal_signing_sessions SET used_at=now() WHERE id=session.id;
  INSERT INTO public.proposal_request_audit_events(proposal_request_id,actor_id,action,notes,proposal_version_id,metadata)
  VALUES(request.id,NULL,'customer_'||p_decision,'Customer decision recorded through one-time signing link',version.id,jsonb_build_object('signing_session_id',session.id));
  INSERT INTO public.proposal_request_notifications(proposal_request_id,user_id,actor_id,notification_type,message)
  SELECT request.id,recipient,NULL,'proposal_'||p_decision,'Customer '||p_decision||' proposal version '||version.version_number||'.' FROM (SELECT request.salesperson_id recipient UNION SELECT request.assigned_estimator_id) recipients WHERE recipient IS NOT NULL;
  RETURN request.id;
END;
$$;
REVOKE ALL ON FUNCTION public.complete_customer_proposal_decision(text,text,text,text,text[]) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.complete_customer_proposal_decision(text,text,text,text,text[]) TO service_role;

CREATE OR REPLACE FUNCTION public.write_proposal_audit(request_id uuid,action_name text,note_text text DEFAULT '',version_id uuid DEFAULT NULL,event_metadata jsonb DEFAULT '{}'::jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  INSERT INTO public.proposal_request_audit_events(proposal_request_id,actor_id,action,notes,proposal_version_id,metadata)
  VALUES(request_id,auth.uid(),action_name,coalesce(note_text,''),version_id,coalesce(event_metadata,'{}'::jsonb));
END;
$$;

CREATE OR REPLACE FUNCTION public.queue_proposal_notification(request_id uuid,recipient_id uuid,kind text,body text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF recipient_id IS NOT NULL AND recipient_id<>auth.uid() THEN
    INSERT INTO public.proposal_request_notifications(proposal_request_id,user_id,actor_id,notification_type,message)
    VALUES(request_id,recipient_id,auth.uid(),kind,body);
  END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.write_proposal_audit(uuid,text,text,uuid,jsonb),public.queue_proposal_notification(uuid,uuid,text,text) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.save_proposal_request(p_request_id uuid,p_payload jsonb)
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE saved public.proposal_requests; current_row public.proposal_requests; request_id uuid:=coalesce(p_request_id,gen_random_uuid());
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF public.current_company_role() NOT IN ('salesperson','admin','cfo') AND NOT public.is_proposal_manager() THEN RAISE EXCEPTION 'Sales or management access required'; END IF;
  IF NOT public.is_proposal_manager() AND coalesce(nullif(p_payload->>'salesperson_id','')::uuid,auth.uid())<>auth.uid() THEN RAISE EXCEPTION 'Salespeople can only create requests assigned to themselves'; END IF;
  IF p_request_id IS NOT NULL THEN
    SELECT * INTO current_row FROM public.proposal_requests WHERE id=p_request_id FOR UPDATE;
    IF NOT FOUND OR NOT public.can_access_proposal_request(p_request_id) THEN RAISE EXCEPTION 'Proposal request not found'; END IF;
    IF NOT public.is_proposal_manager() AND (current_row.salesperson_id<>auth.uid() OR current_row.status NOT IN ('draft','missing_information')) THEN
      RAISE EXCEPTION 'Submitted requests can only be changed through workflow actions';
    END IF;
  END IF;
  INSERT INTO public.proposal_requests(
    id,created_by,salesperson_id,assigned_estimator_id,priority,job_type,existing_lead_job_id,customer_name,property_name,service_address,billing_information,customer_contact,
    project_contact_first_name,project_contact_last_name,project_contact_phone,project_contact_email,
    scope_of_work,roof_areas,roofing_system,work_type,measurements,roof_measurement_notes,total_linear_feet,property_type,story_count,construction_type,
    material_specifications,existing_layers,warranty_requirements,tear_off_details,parapet_wall_measurements,ac_work_details,plywood_fascia_notes,
    detail_component_notes,accessories_needed,deck_material_requirements,shingle_selection,tile_selection,warranty_upgrade_options,subcontractor_requirements,
    roof_access_details,permit_requirements,weekend_work_availability,overspray_risk_notes,parking_zone_sign_locations,special_conditions,exclusions,allowances,alternates,
    estimated_crew_size,estimated_working_days,equipment_requirements,crane_requirements,hvac_requirements,travel_lodging,production_notes,
    estimated_material_quantities,estimated_labor_assumptions,target_price,pricing_notes,margin_markup_assumptions,payment_deposit_terms,deposit_required,
    customer_requests,verbal_commitments,customer_deadline,salesperson_notes,manual_target_at,updated_at)
  VALUES(
    request_id,auth.uid(),coalesce(nullif(p_payload->>'salesperson_id','')::uuid,auth.uid()),nullif(p_payload->>'assigned_estimator_id','')::uuid,
    coalesce(nullif(p_payload->>'priority',''),'normal'),coalesce(nullif(p_payload->>'job_type',''),'standard_roof'),coalesce(p_payload->>'existing_lead_job_id',''),
    coalesce(p_payload->>'customer_name',''),coalesce(p_payload->>'property_name',''),coalesce(p_payload->>'service_address',''),coalesce(p_payload->>'billing_information',''),coalesce(p_payload->>'customer_contact',''),
    coalesce(p_payload->>'project_contact_first_name',''),coalesce(p_payload->>'project_contact_last_name',''),coalesce(p_payload->>'project_contact_phone',''),coalesce(p_payload->>'project_contact_email',''),
    coalesce(p_payload->>'scope_of_work',''),coalesce(p_payload->>'roof_areas',''),coalesce(p_payload->>'roofing_system',''),coalesce(p_payload->>'work_type',''),coalesce(p_payload->>'measurements',''),
    coalesce(p_payload->>'roof_measurement_notes',''),nullif(p_payload->>'total_linear_feet','')::numeric,coalesce(p_payload->>'property_type',''),coalesce(p_payload->>'story_count',''),coalesce(p_payload->>'construction_type',''),
    coalesce(p_payload->>'material_specifications',''),coalesce(p_payload->>'existing_layers',''),coalesce(p_payload->>'warranty_requirements',''),coalesce(p_payload->>'tear_off_details',''),
    coalesce(p_payload->>'parapet_wall_measurements',''),coalesce(p_payload->>'ac_work_details',''),coalesce(p_payload->>'plywood_fascia_notes',''),coalesce(p_payload->>'detail_component_notes',''),
    coalesce(p_payload->>'accessories_needed',''),coalesce(p_payload->>'deck_material_requirements',''),coalesce(p_payload->>'shingle_selection',''),coalesce(p_payload->>'tile_selection',''),
    coalesce(p_payload->>'warranty_upgrade_options',''),coalesce(p_payload->>'subcontractor_requirements',''),coalesce(p_payload->>'roof_access_details',''),coalesce(p_payload->>'permit_requirements',''),
    coalesce(p_payload->>'weekend_work_availability',''),coalesce(p_payload->>'overspray_risk_notes',''),coalesce(p_payload->>'parking_zone_sign_locations',''),
    coalesce(p_payload->>'special_conditions',''),coalesce(p_payload->>'exclusions',''),coalesce(p_payload->>'allowances',''),coalesce(p_payload->>'alternates',''),
    nullif(p_payload->>'estimated_crew_size','')::numeric,nullif(p_payload->>'estimated_working_days','')::numeric,coalesce(p_payload->>'equipment_requirements',''),coalesce(p_payload->>'crane_requirements',''),coalesce(p_payload->>'hvac_requirements',''),coalesce(p_payload->>'travel_lodging',''),coalesce(p_payload->>'production_notes',''),
    coalesce(p_payload->>'estimated_material_quantities',''),coalesce(p_payload->>'estimated_labor_assumptions',''),nullif(p_payload->>'target_price','')::numeric,coalesce(p_payload->>'pricing_notes',''),coalesce(p_payload->>'margin_markup_assumptions',''),coalesce(p_payload->>'payment_deposit_terms',''),coalesce((p_payload->>'deposit_required')::boolean,false),
    coalesce(p_payload->>'customer_requests',''),coalesce(p_payload->>'verbal_commitments',''),nullif(p_payload->>'customer_deadline','')::date,coalesce(p_payload->>'salesperson_notes',''),nullif(p_payload->>'manual_target_at','')::timestamptz,now())
  ON CONFLICT(id) DO UPDATE SET
    salesperson_id=EXCLUDED.salesperson_id,assigned_estimator_id=EXCLUDED.assigned_estimator_id,priority=EXCLUDED.priority,job_type=EXCLUDED.job_type,existing_lead_job_id=EXCLUDED.existing_lead_job_id,
    customer_name=EXCLUDED.customer_name,property_name=EXCLUDED.property_name,service_address=EXCLUDED.service_address,billing_information=EXCLUDED.billing_information,customer_contact=EXCLUDED.customer_contact,
    project_contact_first_name=EXCLUDED.project_contact_first_name,project_contact_last_name=EXCLUDED.project_contact_last_name,project_contact_phone=EXCLUDED.project_contact_phone,project_contact_email=EXCLUDED.project_contact_email,
    scope_of_work=EXCLUDED.scope_of_work,roof_areas=EXCLUDED.roof_areas,roofing_system=EXCLUDED.roofing_system,work_type=EXCLUDED.work_type,measurements=EXCLUDED.measurements,
    roof_measurement_notes=EXCLUDED.roof_measurement_notes,total_linear_feet=EXCLUDED.total_linear_feet,property_type=EXCLUDED.property_type,story_count=EXCLUDED.story_count,construction_type=EXCLUDED.construction_type,
    material_specifications=EXCLUDED.material_specifications,existing_layers=EXCLUDED.existing_layers,warranty_requirements=EXCLUDED.warranty_requirements,tear_off_details=EXCLUDED.tear_off_details,
    accessories_needed=EXCLUDED.accessories_needed,deck_material_requirements=EXCLUDED.deck_material_requirements,shingle_selection=EXCLUDED.shingle_selection,tile_selection=EXCLUDED.tile_selection,
    warranty_upgrade_options=EXCLUDED.warranty_upgrade_options,subcontractor_requirements=EXCLUDED.subcontractor_requirements,roof_access_details=EXCLUDED.roof_access_details,
    permit_requirements=EXCLUDED.permit_requirements,weekend_work_availability=EXCLUDED.weekend_work_availability,overspray_risk_notes=EXCLUDED.overspray_risk_notes,
    parking_zone_sign_locations=EXCLUDED.parking_zone_sign_locations,special_conditions=EXCLUDED.special_conditions,exclusions=EXCLUDED.exclusions,allowances=EXCLUDED.allowances,alternates=EXCLUDED.alternates,
    estimated_crew_size=EXCLUDED.estimated_crew_size,estimated_working_days=EXCLUDED.estimated_working_days,equipment_requirements=EXCLUDED.equipment_requirements,crane_requirements=EXCLUDED.crane_requirements,hvac_requirements=EXCLUDED.hvac_requirements,travel_lodging=EXCLUDED.travel_lodging,production_notes=EXCLUDED.production_notes,
    estimated_material_quantities=EXCLUDED.estimated_material_quantities,estimated_labor_assumptions=EXCLUDED.estimated_labor_assumptions,target_price=EXCLUDED.target_price,pricing_notes=EXCLUDED.pricing_notes,margin_markup_assumptions=EXCLUDED.margin_markup_assumptions,payment_deposit_terms=EXCLUDED.payment_deposit_terms,deposit_required=EXCLUDED.deposit_required,
    customer_requests=EXCLUDED.customer_requests,verbal_commitments=EXCLUDED.verbal_commitments,customer_deadline=EXCLUDED.customer_deadline,salesperson_notes=EXCLUDED.salesperson_notes,manual_target_at=EXCLUDED.manual_target_at,updated_at=now()
  RETURNING * INTO saved;
  PERFORM public.write_proposal_audit(saved.id,CASE WHEN p_request_id IS NULL THEN 'created' ELSE 'draft_updated' END);
  RETURN saved;
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_proposal_request(p_request_id uuid)
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE request public.proposal_requests; missing text[]; estimator uuid; submitted_time timestamptz:=now(); task public.company_tasks;
BEGIN
  SELECT * INTO request FROM public.proposal_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR (request.salesperson_id<>auth.uid() AND request.created_by<>auth.uid() AND NOT public.is_proposal_manager()) THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF request.status NOT IN ('draft','missing_information') THEN RAISE EXCEPTION 'Only draft or missing-information requests can be submitted'; END IF;
  missing:=public.proposal_request_required_missing(to_jsonb(request));
  IF cardinality(missing)>0 THEN RAISE EXCEPTION 'Required information is missing: %',array_to_string(missing,', '); END IF;
  IF request.priority='rush' AND request.rush_approval_status<>'approved' THEN
    UPDATE public.proposal_requests SET rush_approval_status='pending',updated_at=now() WHERE id=request.id RETURNING * INTO request;
    INSERT INTO public.proposal_request_notifications(proposal_request_id,user_id,actor_id,notification_type,message)
      SELECT request.id,id,auth.uid(),'rush_approval_needed','Rush Proposal Request #'||request.request_number||' requires approval.' FROM public.user_profiles WHERE lower(role) IN ('admin','cfo');
    PERFORM public.write_proposal_audit(request.id,'rush_approval_requested'); RETURN request;
  END IF;
  SELECT id INTO estimator FROM public.user_profiles WHERE lower(email)='daniela@crtroofing.com' LIMIT 1;
  estimator:=coalesce(request.assigned_estimator_id,estimator);
  IF estimator IS NULL THEN RAISE EXCEPTION 'No estimator is configured'; END IF;
  IF request.task_id IS NULL THEN
    INSERT INTO public.company_tasks(title,description,status,priority,due_date,related_type,related_id,related_label,created_by,task_type)
    VALUES('Proposal Request: '||request.property_name,request.scope_of_work,'open',CASE request.priority WHEN 'rush' THEN 'urgent' WHEN 'high' THEN 'high' ELSE 'normal' END,request.customer_deadline,'proposal_request',request.id::text,request.customer_name,request.created_by,'proposal_request') RETURNING * INTO task;
    INSERT INTO public.company_task_assignees(task_id,user_id,assigned_by) VALUES(task.id,estimator,auth.uid()) ON CONFLICT DO NOTHING;
  ELSE SELECT * INTO task FROM public.company_tasks WHERE id=request.task_id; END IF;
  UPDATE public.proposal_requests SET task_id=task.id,assigned_estimator_id=estimator,status='submitted',submitted_at=coalesce(submitted_at,submitted_time),
    target_completion_at=coalesce(manual_target_at,CASE job_type WHEN 'complex_commercial' THEN public.add_proposal_business_days(submitted_time,2) WHEN 'large_rfp' THEN manual_target_at ELSE public.add_proposal_business_days(submitted_time,1) END),
    sla_paused_seconds=sla_paused_seconds+CASE WHEN sla_paused_at IS NULL THEN 0 ELSE extract(epoch FROM submitted_time-sla_paused_at)::bigint END,sla_paused_at=NULL,missing_information_notes='',updated_at=now()
  WHERE id=request.id RETURNING * INTO request;
  PERFORM public.queue_proposal_notification(request.id,estimator,'proposal_submitted','A complete Proposal Request is ready for review.');
  PERFORM public.write_proposal_audit(request.id,CASE WHEN request.missing_information_count>0 THEN 'information_resubmitted' ELSE 'submitted' END);
  RETURN request;
END;
$$;

CREATE OR REPLACE FUNCTION public.review_proposal_request(p_request_id uuid,p_action text,p_missing_notes text DEFAULT '',p_target_at timestamptz DEFAULT NULL)
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE request public.proposal_requests;
BEGIN
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager()) THEN RAISE EXCEPTION 'Estimator access required'; END IF;
  SELECT * INTO request FROM public.proposal_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR request.status NOT IN ('submitted','under_review') THEN RAISE EXCEPTION 'Request is not awaiting review'; END IF;
  IF p_action='accept' THEN
    UPDATE public.proposal_requests SET status='under_review',accepted_at=now(),target_completion_at=coalesce(p_target_at,target_completion_at),updated_at=now() WHERE id=p_request_id RETURNING * INTO request;
    PERFORM public.write_proposal_audit(request.id,'assigned','Accepted into estimating queue');
  ELSIF p_action='missing_information' THEN
    IF trim(coalesce(p_missing_notes,''))='' THEN RAISE EXCEPTION 'Missing information details are required'; END IF;
    UPDATE public.proposal_requests SET status='missing_information',missing_information_notes=trim(p_missing_notes),missing_information_count=missing_information_count+1,sla_paused_at=now(),updated_at=now() WHERE id=p_request_id RETURNING * INTO request;
    PERFORM public.queue_proposal_notification(request.id,request.salesperson_id,'missing_information',trim(p_missing_notes));
    PERFORM public.write_proposal_audit(request.id,'information_requested',trim(p_missing_notes));
  ELSE RAISE EXCEPTION 'Invalid review action'; END IF;
  RETURN request;
END;
$$;

CREATE OR REPLACE FUNCTION public.approve_rush_proposal_request(p_request_id uuid,p_approved boolean,p_notes text DEFAULT '')
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE request public.proposal_requests;
BEGIN
  IF NOT public.is_proposal_manager() THEN RAISE EXCEPTION 'Admin/CFO access required'; END IF;
  UPDATE public.proposal_requests SET rush_approval_status=CASE WHEN p_approved THEN 'approved' ELSE 'rejected' END,rush_approved_by=auth.uid(),rush_approved_at=now(),priority=CASE WHEN p_approved THEN priority ELSE 'high' END,updated_at=now() WHERE id=p_request_id AND priority='rush' RETURNING * INTO request;
  IF NOT FOUND THEN RAISE EXCEPTION 'Rush request not found'; END IF;
  PERFORM public.queue_proposal_notification(request.id,request.salesperson_id,'rush_decision',CASE WHEN p_approved THEN 'Rush priority approved.' ELSE 'Rush priority rejected; request changed to High.' END);
  PERFORM public.write_proposal_audit(request.id,CASE WHEN p_approved THEN 'rush_approved' ELSE 'rush_rejected' END,p_notes); RETURN request;
END;
$$;

CREATE OR REPLACE FUNCTION public.manage_proposal_request(p_request_id uuid,p_estimator_id uuid DEFAULT NULL,p_priority text DEFAULT NULL,p_target_at timestamptz DEFAULT NULL)
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE request public.proposal_requests;
BEGIN
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager()) THEN RAISE EXCEPTION 'Estimator or management access required'; END IF;
  IF p_estimator_id IS NOT NULL AND NOT public.is_proposal_manager() THEN RAISE EXCEPTION 'Only management can reassign requests'; END IF;
  IF p_priority IS NOT NULL AND p_priority NOT IN ('normal','high','rush') THEN RAISE EXCEPTION 'Invalid priority'; END IF;
  IF p_priority='rush' AND NOT public.is_proposal_manager() THEN RAISE EXCEPTION 'Rush priority requires admin/CFO approval'; END IF;
  UPDATE public.proposal_requests SET
    assigned_estimator_id=coalesce(p_estimator_id,assigned_estimator_id),
    priority=coalesce(p_priority,priority),
    rush_approval_status=CASE WHEN p_priority='rush' THEN 'approved' ELSE rush_approval_status END,
    rush_approved_by=CASE WHEN p_priority='rush' THEN auth.uid() ELSE rush_approved_by END,
    rush_approved_at=CASE WHEN p_priority='rush' THEN now() ELSE rush_approved_at END,
    target_completion_at=coalesce(p_target_at,target_completion_at),updated_at=now()
  WHERE id=p_request_id AND public.can_access_proposal_request(id) RETURNING * INTO request;
  IF NOT FOUND THEN RAISE EXCEPTION 'Proposal request not found'; END IF;
  PERFORM public.write_proposal_audit(request.id,'management_updated','Estimator, priority, or target date updated'); RETURN request;
END;
$$;

CREATE OR REPLACE FUNCTION public.protect_proposal_notification_update()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF auth.role()='service_role' THEN RETURN NEW; END IF;
  IF NEW.id IS DISTINCT FROM OLD.id OR NEW.proposal_request_id IS DISTINCT FROM OLD.proposal_request_id OR NEW.user_id IS DISTINCT FROM OLD.user_id
    OR NEW.actor_id IS DISTINCT FROM OLD.actor_id OR NEW.notification_type IS DISTINCT FROM OLD.notification_type OR NEW.message IS DISTINCT FROM OLD.message
    OR NEW.email_status IS DISTINCT FROM OLD.email_status OR NEW.email_sent_at IS DISTINCT FROM OLD.email_sent_at OR NEW.email_error IS DISTINCT FROM OLD.email_error
    OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN RAISE EXCEPTION 'Users can only mark proposal notifications as read'; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_protect_proposal_notification_update BEFORE UPDATE ON public.proposal_request_notifications FOR EACH ROW EXECUTE FUNCTION public.protect_proposal_notification_update();

CREATE OR REPLACE FUNCTION public.enqueue_overdue_proposal_notifications()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE inserted_count integer;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Service role required'; END IF;
  INSERT INTO public.proposal_request_notifications(proposal_request_id,user_id,actor_id,notification_type,message)
  SELECT request.id,recipient,NULL,'proposal_overdue','Proposal Request #'||request.request_number||' is overdue.'
  FROM public.proposal_requests request
  CROSS JOIN LATERAL (SELECT request.salesperson_id recipient UNION SELECT request.assigned_estimator_id) recipients
  WHERE request.target_completion_at<now() AND request.status NOT IN ('sent','signed','declined','closed','missing_information') AND recipient IS NOT NULL
    AND NOT EXISTS(SELECT 1 FROM public.proposal_request_notifications notification WHERE notification.proposal_request_id=request.id AND notification.user_id=recipient AND notification.notification_type='proposal_overdue' AND notification.created_at>now()-interval '24 hours');
  GET DIAGNOSTICS inserted_count=ROW_COUNT; RETURN inserted_count;
END;
$$;
REVOKE ALL ON FUNCTION public.enqueue_overdue_proposal_notifications() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_overdue_proposal_notifications() TO service_role;

CREATE OR REPLACE FUNCTION public.save_proposal_change_order(p_request_id uuid,p_description text,p_scope text,p_price numeric,p_required boolean DEFAULT true)
RETURNS public.proposal_change_orders LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE result public.proposal_change_orders;
BEGIN
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager()) OR NOT public.can_access_proposal_request(p_request_id) THEN RAISE EXCEPTION 'Estimator or management access required'; END IF;
  INSERT INTO public.proposal_change_orders(proposal_request_id,description,scope,price,required_for_release)
  VALUES(p_request_id,trim(p_description),trim(p_scope),greatest(coalesce(p_price,0),0),p_required) RETURNING * INTO result;
  PERFORM public.write_proposal_audit(p_request_id,'change_order_created',p_description,NULL,jsonb_build_object('change_order_id',result.id,'price',result.price)); RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.register_proposal_request_attachment(p_request_id uuid,p_category text,p_file_name text,p_storage_path text,p_content_type text DEFAULT '',p_file_size bigint DEFAULT 0)
RETURNS public.proposal_request_attachments LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE result public.proposal_request_attachments;
BEGIN
  IF NOT public.can_access_proposal_request(p_request_id) THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF p_category NOT IN ('photo','measurement','roof_report','drawing','rfp','customer_document','other') THEN RAISE EXCEPTION 'Invalid attachment category'; END IF;
  IF p_storage_path NOT LIKE p_request_id::text||'/%' THEN RAISE EXCEPTION 'Attachment path does not match Proposal Request'; END IF;
  INSERT INTO public.proposal_request_attachments(proposal_request_id,category,file_name,storage_path,content_type,file_size,uploaded_by)
  VALUES(p_request_id,p_category,trim(p_file_name),p_storage_path,coalesce(p_content_type,''),greatest(coalesce(p_file_size,0),0),auth.uid()) RETURNING * INTO result;
  PERFORM public.write_proposal_audit(p_request_id,'attachment_uploaded',result.file_name,NULL,jsonb_build_object('attachment_id',result.id,'category',result.category)); RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_change_order_signing_session(p_change_order_id uuid,p_expires_hours integer DEFAULT 168)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE change_order public.proposal_change_orders; raw_token text:=encode(gen_random_bytes(32),'hex'); expiry timestamptz;
BEGIN
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager()) THEN RAISE EXCEPTION 'Estimator or management access required'; END IF;
  SELECT * INTO change_order FROM public.proposal_change_orders WHERE id=p_change_order_id;
  IF NOT FOUND OR NOT public.can_access_proposal_request(change_order.proposal_request_id) THEN RAISE EXCEPTION 'Change order not found'; END IF;
  expiry:=now()+make_interval(hours=>least(greatest(p_expires_hours,1),720));
  INSERT INTO public.proposal_change_order_signing_sessions(change_order_id,token_hash,expires_at,created_by)
  VALUES(change_order.id,encode(digest(raw_token,'sha256'),'hex'),expiry,auth.uid());
  UPDATE public.proposal_change_orders SET status='sent',updated_at=now() WHERE id=change_order.id;
  PERFORM public.write_proposal_audit(change_order.proposal_request_id,'change_order_sent',change_order.description,NULL,jsonb_build_object('change_order_id',change_order.id,'expires_at',expiry));
  RETURN jsonb_build_object('token',raw_token,'expires_at',expiry,'change_order_id',change_order.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_customer_change_order_signature(p_raw_token text,p_customer_name text,p_signature_path text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE session public.proposal_change_order_signing_sessions; change_order public.proposal_change_orders; scope_entry jsonb;
BEGIN
  IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Service role required'; END IF;
  IF trim(coalesce(p_signature_path,''))='' OR trim(coalesce(p_customer_name,''))='' THEN RAISE EXCEPTION 'Customer name and signature are required'; END IF;
  SELECT * INTO session FROM public.proposal_change_order_signing_sessions WHERE token_hash=encode(digest(p_raw_token,'sha256'),'hex') AND used_at IS NULL AND expires_at>now() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Signing link is invalid or expired'; END IF;
  UPDATE public.proposal_change_orders SET status='signed',customer_signature_storage_path=trim(p_signature_path),customer_signed_at=now(),updated_at=now() WHERE id=session.change_order_id RETURNING * INTO change_order;
  scope_entry:=jsonb_build_object('id',change_order.id,'title','Signed change order','scope',change_order.scope,'price',change_order.price,'customer_approved',true,'change_order',true);
  UPDATE public.proposal_requests SET production_scope=jsonb_set(production_scope,'{authorized}',coalesce(production_scope->'authorized','[]'::jsonb)||jsonb_build_array(scope_entry)),updated_at=now() WHERE id=change_order.proposal_request_id;
  UPDATE public.proposal_change_order_signing_sessions SET used_at=now() WHERE id=session.id;
  INSERT INTO public.proposal_request_audit_events(proposal_request_id,actor_id,action,notes,metadata)
  VALUES(change_order.proposal_request_id,NULL,'change_order_signed',change_order.description,jsonb_build_object('change_order_id',change_order.id,'customer_name',p_customer_name));
  RETURN change_order.proposal_request_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_proposal_deposit_satisfied(p_request_id uuid,p_satisfied boolean)
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE request public.proposal_requests;
BEGIN
  IF NOT (public.is_proposal_manager() OR public.is_company_estimator()) THEN RAISE EXCEPTION 'Estimator or management access required'; END IF;
  UPDATE public.proposal_requests SET deposit_satisfied_at=CASE WHEN p_satisfied THEN now() END,deposit_satisfied_by=CASE WHEN p_satisfied THEN auth.uid() END,updated_at=now()
  WHERE id=p_request_id AND public.can_access_proposal_request(id) RETURNING * INTO request;
  IF NOT FOUND THEN RAISE EXCEPTION 'Proposal request not found'; END IF;
  PERFORM public.write_proposal_audit(request.id,CASE WHEN p_satisfied THEN 'deposit_satisfied' ELSE 'deposit_reopened' END); RETURN request;
END;
$$;

CREATE OR REPLACE FUNCTION public.close_proposal_request(p_request_id uuid,p_notes text DEFAULT '')
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE request public.proposal_requests;
BEGIN
  SELECT * INTO request FROM public.proposal_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR NOT public.can_access_proposal_request(p_request_id) THEN RAISE EXCEPTION 'Proposal request not found'; END IF;
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager() OR request.salesperson_id=auth.uid()) THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF request.status NOT IN ('signed','declined') AND request.production_released_at IS NULL THEN RAISE EXCEPTION 'Only a completed or declined request can be closed'; END IF;
  UPDATE public.proposal_requests SET status='closed',closed_at=now(),updated_at=now() WHERE id=p_request_id RETURNING * INTO request;
  PERFORM public.write_proposal_audit(request.id,'closed',p_notes); RETURN request;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_proposal_to_production(p_request_id uuid,p_override_reason text DEFAULT '')
RETURNS public.proposal_requests LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE request public.proposal_requests; version public.proposal_versions; blockers text[]:='{}'; override_used boolean:=false; new_job_id uuid; new_source_id text;
BEGIN
  IF NOT (public.is_company_estimator() OR public.is_proposal_manager()) THEN RAISE EXCEPTION 'Estimator or management access required'; END IF;
  SELECT * INTO request FROM public.proposal_requests WHERE id=p_request_id FOR UPDATE;
  IF NOT FOUND OR NOT public.can_access_proposal_request(p_request_id) THEN RAISE EXCEPTION 'Proposal request not found'; END IF;
  IF request.production_released_at IS NOT NULL THEN RETURN request; END IF;
  SELECT * INTO version FROM public.proposal_versions WHERE proposal_request_id=p_request_id ORDER BY version_number DESC LIMIT 1;
  IF version.finalized_at IS NULL THEN blockers:=array_append(blockers,'Proposal not finalized'); END IF;
  IF version.sales_approved_at IS NULL THEN blockers:=array_append(blockers,'Salesperson scope approval missing'); END IF;
  IF version.customer_decision<>'signed' OR version.customer_signed_at IS NULL THEN blockers:=array_append(blockers,'Customer signature missing'); END IF;
  IF request.production_scope_generated_at IS NULL OR jsonb_array_length(coalesce(request.production_scope->'authorized','[]'::jsonb))=0 THEN blockers:=array_append(blockers,'Authorized production scope missing'); END IF;
  IF request.deposit_required AND request.deposit_satisfied_at IS NULL THEN blockers:=array_append(blockers,'Required deposit not received'); END IF;
  IF EXISTS(SELECT 1 FROM public.proposal_change_orders WHERE proposal_request_id=p_request_id AND required_for_release AND status<>'signed') THEN blockers:=array_append(blockers,'Required change order not signed'); END IF;
  IF cardinality(blockers)>0 THEN
    IF NOT public.is_proposal_manager() OR trim(coalesce(p_override_reason,''))='' THEN RAISE EXCEPTION 'BLOCKED FROM PRODUCTION: %',array_to_string(blockers,'; '); END IF;
    override_used:=true;
  END IF;
  new_job_id:=gen_random_uuid(); new_source_id:='job:proposal-request:'||request.id;
  INSERT INTO public.active_jobs(id,user_key,source_record_uid,workflow_status,estimate_id,local_estimate_id,job_number,job_name,project_name,customer_name,customer,address,job_address,status,contract_amount,final_bid,project_contact,is_active,created_at,updated_at,updated_by,proposal_request_id,production_authorized_at,production_authorized_by,production_authorization_source,job_payload)
  VALUES(new_job_id,auth.uid()::text,new_source_id,'approved',version.estimate_id,version.estimate_id,'PR-'||request.request_number,request.property_name,request.property_name,request.customer_name,request.customer_name,request.service_address,request.service_address,'Ready for Production',coalesce(request.target_price,0),coalesce(request.target_price,0),request.customer_contact,true,now(),now(),auth.uid()::text,request.id,now(),auth.uid(),CASE WHEN override_used THEN 'admin_override' ELSE 'signed_proposal' END,
    jsonb_build_object('proposalRequestId',request.id,'proposalVersionId',version.id,'workflowStatus','approved','status','Ready for Production','projectStatus','Ready for Production','projectName',request.property_name,'customerName',request.customer_name,'projectAddress',request.service_address,'projectContact',concat_ws(' ',request.project_contact_first_name,request.project_contact_last_name),'projectContactPhone',request.project_contact_phone,'projectContactEmail',request.project_contact_email,'authorizedScope',request.production_scope->'authorized','notAuthorizedScope',request.production_scope->'not_authorized','productionGateOverride',override_used))
  ON CONFLICT(source_record_uid) DO UPDATE SET job_payload=EXCLUDED.job_payload,status=EXCLUDED.status,updated_at=now(),updated_by=auth.uid()::text RETURNING id INTO new_job_id;
  UPDATE public.proposal_requests SET production_released_at=now(),production_released_by=auth.uid(),production_override_reason=CASE WHEN override_used THEN trim(p_override_reason) ELSE '' END,active_job_id=new_job_id,updated_at=now() WHERE id=p_request_id RETURNING * INTO request;
  PERFORM public.write_proposal_audit(request.id,CASE WHEN override_used THEN 'production_override' ELSE 'production_released' END,CASE WHEN override_used THEN p_override_reason ELSE 'All release controls satisfied' END,version.id,jsonb_build_object('blockers',blockers,'active_job_id',new_job_id));
  IF override_used THEN
    INSERT INTO public.proposal_request_notifications(proposal_request_id,user_id,actor_id,notification_type,message)
    SELECT request.id,id,auth.uid(),'production_override','Production gate overridden: '||p_override_reason FROM public.user_profiles WHERE lower(role) IN ('admin','cfo') AND id<>auth.uid();
  END IF;
  RETURN request;
END;
$$;

-- This guard applies only to jobs created by the new proposal workflow. Legacy
-- and manually managed jobs retain their existing behavior during migration.
CREATE OR REPLACE FUNCTION public.block_unauthorized_proposal_production_start()
RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN
  IF NEW.proposal_request_id IS NOT NULL
    AND lower(coalesce(NEW.workflow_status,''))='active'
    AND (TG_OP='INSERT' OR lower(coalesce(OLD.workflow_status,''))<>'active')
    AND NEW.production_authorized_at IS NULL THEN
    RAISE EXCEPTION 'BLOCKED FROM PRODUCTION: signed or administratively authorized scope is required';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_block_unauthorized_proposal_production_start ON public.active_jobs;
CREATE TRIGGER trg_block_unauthorized_proposal_production_start BEFORE INSERT OR UPDATE OF workflow_status ON public.active_jobs
FOR EACH ROW EXECUTE FUNCTION public.block_unauthorized_proposal_production_start();

REVOKE ALL ON FUNCTION public.save_proposal_request(uuid,jsonb),public.submit_proposal_request(uuid),public.review_proposal_request(uuid,text,text,timestamptz),public.approve_rush_proposal_request(uuid,boolean,text),public.manage_proposal_request(uuid,uuid,text,timestamptz),public.save_proposal_version(uuid,jsonb,text,text,text,boolean),public.approve_proposal_scope(uuid,text),public.create_proposal_signing_session(uuid,integer),public.save_proposal_change_order(uuid,text,text,numeric,boolean),public.register_proposal_request_attachment(uuid,text,text,text,text,bigint),public.create_change_order_signing_session(uuid,integer),public.set_proposal_deposit_satisfied(uuid,boolean),public.close_proposal_request(uuid,text),public.release_proposal_to_production(uuid,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.save_proposal_request(uuid,jsonb),public.submit_proposal_request(uuid),public.review_proposal_request(uuid,text,text,timestamptz),public.approve_rush_proposal_request(uuid,boolean,text),public.manage_proposal_request(uuid,uuid,text,timestamptz),public.save_proposal_version(uuid,jsonb,text,text,text,boolean),public.approve_proposal_scope(uuid,text),public.create_proposal_signing_session(uuid,integer),public.save_proposal_change_order(uuid,text,text,numeric,boolean),public.register_proposal_request_attachment(uuid,text,text,text,text,bigint),public.create_change_order_signing_session(uuid,integer),public.set_proposal_deposit_satisfied(uuid,boolean),public.close_proposal_request(uuid,text),public.release_proposal_to_production(uuid,text) TO authenticated;
REVOKE ALL ON FUNCTION public.complete_customer_change_order_signature(text,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.complete_customer_change_order_signature(text,text,text) TO service_role;

INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types) VALUES
('proposal-request-files','proposal-request-files',false,26214400,ARRAY['image/jpeg','image/png','image/webp','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=EXCLUDED.file_size_limit,allowed_mime_types=EXCLUDED.allowed_mime_types;

CREATE POLICY proposal_request_files_read ON storage.objects FOR SELECT TO authenticated
USING(bucket_id='proposal-request-files' AND public.can_access_proposal_request(((storage.foldername(name))[1])::uuid));
CREATE POLICY proposal_request_files_insert ON storage.objects FOR INSERT TO authenticated
WITH CHECK(bucket_id='proposal-request-files' AND public.can_access_proposal_request(((storage.foldername(name))[1])::uuid));

DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.proposal_requests; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.proposal_request_notifications; EXCEPTION WHEN duplicate_object THEN NULL; END;
  END IF;
END $$;

COMMIT;
